In [8]:
import pandas as pd
from bs4 import BeautifulSoup

In [130]:
grades = open('raw.html', 'r')
bs = BeautifulSoup(grades,'lxml')

chunks = bs.find_all('table')
print '%d chunks'%len(chunks)
table = str(chunks[3])
data = pd.read_html(table)
# 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
# 0-1-3-/4-5-7-/8-9-11-/12-13-15-/16-17-19
wf = data[-1]

24 chunks

In [135]:
table = str(chunks[7])
data = pd.read_html(table)
# 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
# 0-1-3-/4-5-7-/8-9-11-/12-13-15-/16-17-19
wf = data[-1]

In [136]:
wf

,0,1,2,3,4,5,6
0,NaN,CrÃ©ditos,3,Nivel,4,Veces,2.0
1,NaN,SecciÃ³n,3,Docente,"Ramos Ponce, Oscar EfraÃ­n",NaN,NaN
2,NaN,Formula,30% EF + 30% EP + 25% Prom.Pa + 15% Pb,NaN,NaN,NaN,NaN
3,NaN,Tipo,EvaluaciÃ³n,Se elimina?,Peso,Nota,NaN
4,NaN,Pa 1,PrÃ¡ctica de Aula,SÃ­,1,16,NaN
5,NaN,Pa 2,PrÃ¡ctica de Aula,SÃ­,1,11,NaN
6,NaN,Pa 3,PrÃ¡ctica de Aula,SÃ­,1,12,NaN
7,NaN,Pa 4,PrÃ¡ctica de Aula,SÃ­,1,16,NaN
8,NaN,Pb 1,Laboratorio,No,1,17,NaN
9,NaN,EP,Examen Parcial Escrito,No,1,11,NaN
10,NaN,EF,Examen Final Escrito,No,1,10,NaN
11,NaN,Observaciones,-,NaN,NaN,NaN,NaN
12,NaN,Nota Final,13,NaN,NaN,NaN,NaN

In [132]:
for i in range(3, 24, 4):
    # chunks[i]
    rdata = pd.read_html(str(chunks[i-3]))   
    for_metadata = rdata[0]
    
    code = for_metadata.loc[0, 4]
    name = for_metadata.loc[2, 4]
    teacher = for_metadata.loc[5, 4]
    credits = for_metadata.loc[4, 2]
    formula = for_metadata.loc[6, 2]
    
    rdata = pd.read_html(str(chunks[i]))
    grades_table = rdata[-1]
    print code, name, teacher, credits, formula

EG0009 Proyecto Interdisciplinario III Egorovna De Denegri, Â LudmilaÂ  Volodina 2 10% Prom.COM + 50% Prom.ING + 30% Prom.PM&E + 10% Prom.TEAM
EL4002 Modelado y SimulaciÃ³n Ramos Ponce, Oscar EfraÃ­n 3 30% EF + 30% EP + 25% Prom.Pa + 15% Pb
EL5002 AnÃ¡lisis de SeÃ±ales y Sistemas Rojas Gomez, Renan Alfredo 5 20% EF + 20% EP + 35% Prom.Pa + 25% Prom.Pb
EL5005 DiseÃ±o de Computadoras Tomas Horna, Chris Dennis 5 30% EF + 40% Prom.Pa + 30% Prom.Pb
GH4002 InglÃ©s III Laos Solari, Aldo 3 30% Prom.EE + 20% EO + 20% Prom.PRO + 15% PyA + 15% TA
MT0014 Control Inteligente Campion, Joseph Frederick 4 25% EF + 30% Prom.Pa + 25% Prom.Pb + 20% Prom.TA

In [122]:
wf.loc[:,5]

0     Veces
1       NaN
2       NaN
3      Nota
4        16
5        11
6        12
7        16
8        17
9        11
10       10
11      NaN
12      NaN
Name: 5, dtype: object